app/json/patternmatching.json

In:
val secondElement = List(1) match {
case x :: y :: xs => xs
case _ => 0
}
the second line should be:
case x :: y :: xs => y

Fix 3rd secondElement definition in patternmatching.json

---

app/json/iterables.json

Added example showing that sameElements returns false when elements of the lists are in a different order.
Added example and explanation of the surprising behaviour of sameElements with small Sets.
Addresses issue #18

More precise explanation of sameElements, addressing issue #18

---

app/json/iterables.json

E.g says that
```scala
Iterable(x1, x2, x3) zipAll (Iterable(y1, y2), x, y) will return ((x1,y1), (x2, y2, y))
```
but must return
```scala
Iterable(x1, x2, x3) zipAll (Iterable(y1, y2), x, y) will return ((x1,y1), (x2, y2), (x3, y)))
```
Additionaly, this example is added, it shows the contrary case
```scala
va xs = List(3, 5)
val ys = List("Bob", "Ann", "Stella")
(xs zipAll(ys, -1, "?")) should be(List((3,"Bob"), (5,"Ann"), (-1,"Stella")))
```

zipall E.g. is fixed added E.g. of contrary case

---

app/json/higherorderfunctions.json

The description of the code block says that the type parameters can be blocked out, but the `isInstanceOf` was using `Function1[Int,Int]` instead of `Function1[_, _]`

Change Int type to underscore

---

app/json/higherorderfunctions.json

Just making it more readable. There was an additional "is"

Tiny grammar fix

---

build.sbt
project/plugins.sbt

Issue #59 
This PR:
* Includes the `wartremover` plugin
* Adds a new `commonSetting` declaration to reuse it in all projects definitions
Now, the *broken rules* are marked as warnings. I'm wondering if we can include some rules as erros. My candidates are:
* [ListOps](https://github.com/puffnfresh/wartremover/blob/1e779589235f7ee3447f0e8c8996b9fcd259d267/README.md#listops)
* [Null](https://github.com/puffnfresh/wartremover/blob/1e779589235f7ee3447f0e8c8996b9fcd259d267/README.md#null)
* [Return](https://github.com/puffnfresh/wartremover/blob/1e779589235f7ee3447f0e8c8996b9fcd259d267/README.md#return)
Please @raulraja could you review? Thanks
@rafaparadela thoughts?

Issue 59 - Includes wartremover

---

scala-exercises-server/app/models/UserModel.scala
scala-exercises-server/conf/application.conf

This updates the project to use a local H2 DB (persisted to `~/.scala-exercises/db`) when `sbt run` is performed. Previously, Postgres was required to be running locally.

Use local H2 DB when running application server

---

app/json/partiallyappliedfunctions.json

Fixed issue in which multiplyCurriedFour(4) incorrectly validates against 12 instead of the correct answer of 16.
Also fixed issue with 'val multiplyCurriedFour=multiplyCurried(4) _' which fails in Scala REPL.  
Replaced with 'val multiplyCurriedFour=multiplyCurried(4)'.

Fixed issues with partiallyappliedfunctions.json

---

app/json/options.json

The type of "result1" indicated in the text refers to a previous exercise.
The correct type of "result1" in the last exercise is "Int".

Options - Reorder post-paragraph to avoid confusion

---

app/json/implicits.json

Previously:
howMuchCanIMake_?(30)
howMuchCanIMake_?(95,95)
This did not show that the second call was overrriding the 'amount' 34 with 95, because hours changed from 30 to 95 too. 
New version:
howMuchCanIMake_?(30)
howMuchCanIMake_?(30,95) // the answer 2850 is also updated.

Preferred default arguments

---

site/client/src/main/scala/config/Routes.scala
site/server/app/com/fortysevendeg/exercises/models/UserQueries.scala
site/server/conf/application.conf
site/server/conf/evolutions/default/1.sql

This PR resolves the issues:
- Evolution sql written as mysql style, instead of postgreslq.
- Unable to find the route to call the evaluation endpoint.
@andyscott  you should be able to have your stuff working once this PR is merged into version-2.
@juanpedromoreno  you should be able to run the ajax call to `evaluate` exercises in the client.
Note: 
- Remember to setup a postgres database called `scalaexercises`
@raulraja @dialelo Could you take a look please? thank you.

Fixing evolution & evaluate ajax call

---

site/server/conf/application.conf

This PR solves #165 , I have:
- created a new developer application under 47deg account.
- set two environment variables for Heroku app `GITHUB_CLIENT_ID` and `GITHUB_CLIENT_SECRET`.
- added two overriding params in `application.conf` to get these variables in prod.
We need this PR in order to have the oAuth flow enabled in production environment.
@dialelo @raulraja @FPerezP @juanpedromoreno Could you review please? Thank you.

Add env. vars for GitHub integration

---

core/compiler/src/main/scala/com/fortysevendeg/exercises/compiler/DocParser.scala
core/compiler/src/test/scala/com/fortysevendeg/exercises/compiler/DocParserSpec.scala

changes in c0de1e8
- @dialelo's regression for #182 
changes in 65f767e
- fixes #182 
- unblocks #167
changes in  8e58f0b
- improved whitespace trimming logic
- improved parsing tests as a whole

Various compiler updates and fixes, round 2

---

core/compiler/src/main/scala/com/fortysevendeg/exercises/compiler/Compiler.scala
core/compiler/src/main/scala/com/fortysevendeg/exercises/compiler/DocParser.scala
core/compiler/src/main/scala/com/fortysevendeg/exercises/compiler/SourceTextExtraction.scala
core/compiler/src/test/scala/com/fortysevendeg/exercises/compiler/DocParserSpec.scala
core/compiler/src/test/scala/com/fortysevendeg/exercises/compiler/SourceTextExtractionSpec.scala
core/sbt-exercise/src/sbt-test/sbt-exercise/basic/src/main/exercises/stdlib/BarSection.scala
core/sbt-exercise/src/sbt-test/sbt-exercise/basic/src/main/exercises/stdlib/FooSection.scala
core/sbt-exercise/src/sbt-test/sbt-exercise/basic/src/main/exercises/stdlib/SampleLibrary.scala
site/client/src/main/scala/utils/DomHandler.scala
site/content/src/main/exercises/foolib/BarSection.scala
site/content/src/main/exercises/foolib/FooSection.scala
site/content/src/main/exercises/foolib/SampleLibrary.scala
site/content/src/main/exercises/shapeless/HListExercises.scala
site/content/src/main/exercises/shapeless/ShapelessLib.scala
site/content/src/main/exercises/stdlib/ClassExercises.scala
site/content/src/main/exercises/stdlib/StdLib.scala
site/server/app/views/templates/home/libraryGridItem.scala.html

This is a minimal implementation that properly handles doc comments when generating libraries. It piggybacks on the scaladoc compiler's doc parsing. And, unfortunately, in one place I used a big rip of scalac code that was marked private. I'd really like to rewrite that ripped segment-- but it's lower priority than the other items needed for the upcoming demo.
One important change is that I am using the doc comment's 'summary' feature to capture the name of libraries/sections/exercises. This means that you must insert an empty line to separate your name from your description in all of your doc comments.
**_No longer valid:_**
/** This is the name
* This is the description.
* This is more description.
*/
**_Required form:_**
/** This is the name
*
* This is the description.
* This is more …

Proper doc comment parsing

---

site/server/app/com/fortysevendeg/exercises/controllers/ApplicationController.scala

We were always using the first library when we needed to actually search for the correct one. This is a quick little fix for the bug.

Use proper library for a given section when loading library index page

---

core/compiler/src/main/scala/com/fortysevendeg/exercises/compiler/Compiler.scala
core/compiler/src/main/scala/com/fortysevendeg/exercises/compiler/TreeGen.scala
core/compiler/src/test/scala/com/fortysevendeg/exercises/compiler/TreeGenSpec.scala
core/runtime/src/main/scala/com/fortysevendeg/exercises/model.scala

This should ultimately bring support for evaluating simple exercises.
I've updated the compiler to output the fully qualified method name for evaluating the exercise. An example path might be `stdlib.ClassExercises.classExercise1` where `stdlib` is a package, `ClassExercises` is an object implementing the `exercise.Section` trait, and `classExercise1` is a method that can be invoked via reflection.
I am blocked on implementing the rest of this as I am unable to log in on a locally running instance and the eval route requires authentication. How should I proceed?

Support evaluating exercise

---

site/server/app/com/fortysevendeg/exercises/models/UserModel.scala
site/server/app/com/fortysevendeg/exercises/utils/OAuth2.scala
site/server/conf/evolutions/default/1.sql
site/server/test/ArbitraryInstances.scala
site/server/test/UserQueriesSpec.scala
site/server/test/UserStoreSpec.scala
site/shared/src/main/scala/shared/User.scala

Users may set their GitHub email to private, which results in a `null` in the JSON payload received during the Oauth cycle. (See https://developer.github.com/v3/users/#get-a-single-user)
Previously an exception was thrown because the unmarshaller didn't expect the null. This fix changes the email field to an `Option[String]`, after demarshalling.
It also lets me log in to the app, because I'm one of said users!

Allow user emails to be null

---

site/server/test/com/fortysevendeg/exercises/persistence/PersistenceModuleSpec.scala
site/server/test/com/fortysevendeg/exercises/support/ArbitraryInstances.scala

This PR accomplish the technical debt acquired the last week. Now, all our persistence tests are using the same arbitrary instances together with the shapeless scalacheck impl. Please, @raulraja could you review? Thanks.

JP - Unifies the arbitrary instances in the PersistenceModuleSpec file

---

site/client/src/main/scala/Model.scala

As a result of the issue #240, I noticed that once an exercises is successfully evaluated, is not possible running the evaluation again.
I guess the right behaviour is allow that exercises can be evaluated once and again. So this PR set the exercise as unsolved when is changed (although it had been set as solved previously), allowing to run the evaluation again.
@raulraja @dialelo Does this make sense for you?

Set the exercise as Unsolved when it's changed after a succeeded evaluation

---

site/content/src/main/exercises/shapeless/HListExercises.scala
site/content/src/main/exercises/shapeless/PolyExercises.scala
site/content/src/main/exercises/stdlib/PatternMatching.scala
site/content/src/main/exercises/stdlib/StdLib.scala
site/server/app/views/templates/library/index.scala.html

This PR:
Ticket: #213 
The result:
@raulraja @dialelo Could you review please? Thank you.

Renamed Libraries and Sections without spaces

---

site/server/app/assets/stylesheets/layout/_sidebar.scss
site/server/app/com/fortysevendeg/exercises/controllers/ApplicationController.scala
site/server/app/com/fortysevendeg/exercises/services/free/userprogressops.scala
site/server/app/views/templates/library/index.scala.html
site/server/app/views/templates/library/sectionRow.scala.html
site/shared/src/main/scala/shared/User.scala

Involves two things:
An example with a completed section (Identity is finished but I'm looking at Xor):
Another with no complete sections:

Show section progress

---

core/build.sbt
core/compiler/src/main/scala/com/fortysevendeg/exercises/compiler/DocParser.scala

- Had to wrap the code in an `object` because the code to format has to be in an object or a class and not all examples are like that. When unwrapping I make sure to trim the leading whitespace that Scalariform adds to the body of the object.
- I run the formatting in`Xor.catchNonFatal` because the `format` method happily throws exceptions. When having a piece of non-Scala code (for example a session in the REPL) or code that can't be parsed we return it verbatim.
@raulraja @rafaparadela @juanpedromoreno @andyscott take a look please!

Format code samples with Scalariform

---

site/server/app/com/fortysevendeg/exercises/controllers/ApplicationController.scala
site/server/app/com/fortysevendeg/exercises/services/ExercisesService.scala
site/server/conf/application.conf
site/server/test/com/fortysevendeg/exercises/services/ExercisesServiceSpec.scala

Added a new configuration option: `exercises.top_libraries`, that will contain an array with the names of the libraries we want to show on top in the homepage. @raulraja @juanpedromoreno please take look!

Configure top library order for homepage

---

core/compiler/src/main/scala/com/fortysevendeg/exercises/compiler/DocParser.scala
site/server/app/com/fortysevendeg/exercises/controllers/ApplicationController.scala
site/server/app/com/fortysevendeg/exercises/controllers/ExercisesController.scala
site/server/app/com/fortysevendeg/exercises/services/ExercisesService.scala
site/shared/src/main/scala/shared/Exercise.scala

This updates the core project so that exercise exceptions thrown by scalatest are handled in a special manner.
I chose to change the exercise evaluation result to a new type. The left projection is a simple error message, while the right projection is the success value. This simplifies logic in the exercise controller.

Change bubble up behavior of scalatest exceptions in exercises

---

site/server/app/com/fortysevendeg/exercises/persistence/repositories/UserProgressRepository.scala
site/server/app/com/fortysevendeg/exercises/services/free/userprogressops.scala

@juanpedromoreno @raulraja take a look, the problem with the `findByUserIdAggregated` is that it retrieves the completed exercise count and what we want is the count of completed sections.

Show the completed sections instead of the completed exercises

---

site/server/app/com/fortysevendeg/exercises/ApplicationLoader.scala
site/server/app/com/fortysevendeg/exercises/utils/OAuth2.scala
site/server/conf/application.conf
site/server/conf/application.dev.conf

This PR:
- Adds several env vars for deploying in Heroku.
- Apply a condition to redirect after logging: If the referrer doesn't exist or it's github then go to home, in other case return back to the referrer. 
@raulraja @dialelo @juanpedromoreno @FPerezP Could you review please?
Notes: I have deployed these advances in Heroku, so you can try to authorize to the app again in GitHub (pay attention: [THIS LINK IS FOR REVOKING AUTHORIZATION](https://github.com/settings/applications#revoke_authorization_5bfd3164c06442db5644))
[Deployed app](http://scala-exercises.herokuapp.com/)

Redefines deployment settings and auth process

---

site/content/src/main/exercises/catslib/FunctorSection.scala
site/server/app/com/fortysevendeg/exercises/controllers/JsonFormats.scala

I implemented the JSON read wrongly, which broke the evaluation from client HTTP requests :blush: It's now fixed along with a minor fix to one of the exercises.

Fix regressions introduced by #286

---

site/server/app/com/fortysevendeg/exercises/controllers/ApplicationController.scala
site/server/app/com/fortysevendeg/exercises/persistence/repositories/UserRepository.scala
site/server/app/com/fortysevendeg/exercises/services/free/userops.scala
site/server/app/com/fortysevendeg/exercises/utils/OAuth2.scala
site/server/test/com/fortysevendeg/exercises/persistence/repositories/UserRepositorySpec.scala

@raulraja @rafaparadela @juanpedromoreno take a look and let me know if something is missing.

Cleanup Oauth code

---

README.md
core/build.sbt

This PR fixes, on one hand, the conflicting cross-version suffixes in org.scalariform (2.10, 2.11). On the other hand, try to clarify what could the user do in case of runtime exceptions.
Fixes: https://github.com/scala-exercises/scala-exercises/issues/293
Please, @raulraja @dialelo Could you review? Thanks.

JP SE-293 Transitive Dependency issues with Ensime/Scalariform

---

site/content/src/main/scala/shapeless/ArityExercises.scala
site/content/src/main/scala/shapeless/CoproductExercises.scala
site/content/src/main/scala/shapeless/ExtensibleRecordsExercises.scala
site/content/src/main/scala/shapeless/GenericExercises.scala
site/content/src/main/scala/shapeless/HListExercises.scala
site/content/src/main/scala/shapeless/HMapExercises.scala
site/content/src/main/scala/shapeless/PolyExercises.scala
site/content/src/main/scala/shapeless/ShapelessLib.scala
site/content/src/main/scala/shapeless/SingletonExercises.scala
site/content/src/main/scala/shapeless/SingletonTypedSymbolsExercises.scala
site/content/src/main/scala/shapeless/TuplesExercises.scala
site/content/src/main/scala/stdlib/Implicits.scala
site/content/src/main/scala/stdlib/InfixPrefixandPostfixOperators.scala
site/content/src/main/scala/stdlib/Traversables.scala

This is a rebase of changes from #313. It's only the changes related to the shapeless exercises. Scalariform formatting of exercises still needs to be checked (and a separate PR submitted, if needed).

Improve shapeless exercises

---

core/compiler/src/main/scala/com/fortysevendeg/exercises/compiler/comments.scala
core/compiler/src/test/scala/com/fortysevendeg/exercises/compiler/CommentParsingRenderingSpec.scala
core/compiler/src/test/scala/com/fortysevendeg/exercises/compiler/CommentRenderingRegressions.scala

This fixes the formatting bug for certain code blobs in exercise comments. It should close #309.

Fix behavior of code formatter for comments.

---

README.md

From the documentation, the parameter for running a command is "-c", not "-C" (http://www.postgresql.org/docs/9.4/static/app-psql.html)

Fix wrong parameter of "psql" when creating the db

---

core/build.sbt
core/compiler/src/main/scala/com/fortysevendeg/exercises/compiler/Compiler.scala
core/compiler/src/main/scala/com/fortysevendeg/exercises/compiler/TreeGen.scala
core/compiler/src/test/scala/com/fortysevendeg/exercises/compiler/TreeGenSpec.scala
core/runtime-example/src/main/scala/com.fortysevendeg.exercises/Example.scala
core/runtime/src/main/scala/com/fortysevendeg/exercises/Evaluator.scala
core/runtime/src/main/scala/com/fortysevendeg/exercises/MethodEval.scala
core/runtime/src/main/scala/com/fortysevendeg/exercises/Security.scala
core/runtime/src/main/scala/com/fortysevendeg/exercises/model.scala
core/runtime/src/test/scala/com/fortysevendeg/exercises/MethodEvalSpec.scala
core/sbt-exercise/src/sbt-test/sbt-exercise/basic/check/src/main/scala/check.scala
site/build.sbt
site/project/plugins.sbt
site/server/app/com/fortysevendeg/exercises/services/ExercisesService.scala

* Evaluator produce an EvalResult[T] it has more information than the original EvaluationResult[T]
double check to see what can be bubble back to the ui
* RangePosition in CompilationInfo would need to be shifted (see wrapedCode in eval[T])
* I'm using sbt BuildInfo in ExerciceService to find the correct classpath (artifacts). This would changed when deployed.
I'm not too familiar with Play dependency injection, it's up to you guys to figure it out.
* MethodEval security (jvm SecurityManager) is off by default in ExercisesService. Play and sbt are running on the same jvm. It should work fine when deployed.

Implement Evaluator based on Scala Compiler

---

server/app/com/fortysevendeg/exercises/ApplicationLoader.scala
server/conf/application.conf
server/conf/application.dev.conf
server/test/com/fortysevendeg/exercises/persistence/repositories/UserProgressRepositorySpec.scala

@raulraja @rafaparadela plz take a look, this will avoid running evolutions automatically in production. During development, Play will detect schema changes and prompt you to apply them when running the app.

Disable automatic running of evolutions on app load

---

build.sbt
compiler/src/main/scala/com/fortysevendeg/exercises/compiler/Compiler.scala
compiler/src/main/scala/com/fortysevendeg/exercises/compiler/SourceTextExtraction.scala
compiler/src/main/scala/com/fortysevendeg/exercises/compiler/TreeGen.scala
compiler/src/test/scala/com/fortysevendeg/exercises/compiler/CompilerSpec.scala
compiler/src/test/scala/com/fortysevendeg/exercises/compiler/SourceTextExtractionSpec.scala
compiler/src/test/scala/com/fortysevendeg/exercises/compiler/TreeGenSpec.scala
definitions/src/main/scala/exercise/Library.scala
runtime/src/main/scala/com/fortysevendeg/exercises/Exercises.scala
runtime/src/main/scala/com/fortysevendeg/exercises/model.scala
runtime/src/test/scala/com/fortysevendeg/exercises/Content.scala
sbt-exercise/src/main/scala/com/fortysevendeg/exercises/sbtexercise/ExerciseCompilerPlugin.scala
server/app/com/fortysevendeg/exercises/ApplicationLoader.scala
server/app/com/fortysevendeg/exercises/app.scala
server/app/com/fortysevendeg/exercises/controllers/ApplicationController.scala
server/app/com/fortysevendeg/exercises/controllers/OAuthController.scala
server/app/com/fortysevendeg/exercises/persistence/domain/UserQueries.scala
server/app/com/fortysevendeg/exercises/services/ExercisesService.scala
server/app/com/fortysevendeg/exercises/services/free/GithubOps.scala
server/app/com/fortysevendeg/exercises/services/interpreters/interpreters.scala
server/app/com/fortysevendeg/exercises/utils/OAuth2.scala
server/app/views/templates/library/commits_modal.scala.html
server/app/views/templates/library/contributors.scala.html
server/app/views/templates/library/footer.scala.html
server/app/views/templates/library/index.scala.html
server/conf/application.conf
server/conf/routes
shared/src/main/scala/shared/Contribution.scala
shared/src/main/scala/shared/Exercise.scala

This PR includes:
- Addition of `owner` and `repository` in Library model.
- Inferring those fields during compilation.
- Integration of Github4s to interact with Github.
- Changes in templates to show contributors, commits, links to editing, etc.
@raulraja Could you review please? Thank you.
FYI Most of these changes were reviewed in this PR: https://github.com/scala-exercises/site/pull/345

GitHub interaction

---

compiler/src/main/scala/com/fortysevendeg/exercises/compiler/Compiler.scala

This PR fixes #396 . It get an environment variable called `GITHUB_TOKEN` in order to avoid the rate limit exception.
So, you should [create a new personal access token with `repo` scope](https://github.com/settings/tokens/new) and create an env var called `GITHUB_TOKEN` with it.
@dialelo Could you review please? Thank you.

Retrieve a valid access token for Github requests

---

compiler/src/main/scala/com/fortysevendeg/exercises/compiler/SourceTextExtraction.scala
compiler/src/test/scala/com/fortysevendeg/exercises/compiler/SourceTextExtractionSpec.scala

Fixes a bug we found in the compiler: emitting the imports in reverse order. @raulraja @rafaparadela please take a look.

Accumulate imports in order

---

server/conf/application.conf

This PR closes #404.
- In prod, database connection data is retrieved from `HEROKU_POSTGRESQL_ORANGE_URL`.
- In preview apps, from `DATABASE_URL` (generated dynamically by Heroku).
@raulraja @dialelo  Makes sense to you both?

Rename database url env var

---

.gitignore
build.sbt
compiler/src/main/scala/com/fortysevendeg/exercises/compiler/Compiler.scala
compiler/src/main/scala/com/fortysevendeg/exercises/compiler/TreeGen.scala
compiler/src/test/scala/com/fortysevendeg/exercises/compiler/TreeGenSpec.scala
runtime/src/main/scala/com/fortysevendeg/exercises/Exercises.scala
runtime/src/test/scala/com/fortysevendeg/exercises/Content.scala
runtime/src/test/scala/com/fortysevendeg/exercises/LibraryDiscoverySpec.scala
sbt-exercise/src/main/scala/com/fortysevendeg/exercises/sbtexercise/ExerciseCompilerPlugin.scala
sbt-exercise/src/sbt-test/sbt-exercise/basic/test

And change the target package from `defaultLib` for the more semantic
`scalaExercisesContent`. Closes #458

Uniquify generated exercise and section names

---

build.sbt

For avoiding accidentaly introduced incompatibilities between the
content, runtime and the site I've decided to not continue using wildcard
version specs like 0.1.+. This means that each time we want to publish
the content we'll have to bump the content repos *and* the site, but is
an extra check that can avoid problems introduced by automatic
deployments like in #490

Version the content and site together

---

compiler/src/main/scala/org/scalaexercises/exercises/compiler/Compiler.scala
compiler/src/test/scala/org/scalaexercises/exercises/compiler/CompilerSpec.scala
sbt-exercise/src/main/scala/org/scalaexercises/exercises/sbtexercise/ExerciseCompilerPlugin.scala

This PR fixes #502 by adding a new `SettingKey` for not fetching contributions on compilation
The default value is `true`. You can modify this value in your "exercises" repo:
*In the SBT session*
```bash
> set ExerciseCompilerPlugin.fetchContributors := false
```
*In the `build.sbt`*
```scala
.settings(
//...
ExerciseCompilerPlugin.fetchContributors := false
)
```
Please @dialelo @raulraja could you review? Thanks

Adds setting for not fetching contributions on compilation

---

DEV_GUIDE.md

This PR is meant to improve the current Development Guide to add a new section about the current known limitations of the Scala Exercises platform. It also adds a reference to the new bare-bones template that we've added to make it easier to create content libraries.
Could you please take a look at it, @dialelo @raulraja @juanpedromoreno @noelmarkham? Thanks!!

Added section for current known limitations and reference to template project

---

compiler/src/main/scala/org/scalaexercises/exercises/compiler/Compiler.scala
compiler/src/test/scala/org/scalaexercises/exercises/compiler/CompilerSpec.scala

This pull request adds a new functionality that allows the compiler to check if the sections list of a `Library` object is empty.
If the list is empty, the compiler will throw an error like:
This PR closes #511 
```
Unable to create SampleLibrary: A Library object must contain at least one section
```
@raulraja @dialelo Please review at your convenience. Thanks!

Prevents empty sections list for Library objects

---

README.md

Instead of running the database on the system directly, it can also be started inside a docker container. This pull requests adds a section about that to the Readme.

Add Docker instructions to Readme

---

README.md

As suggested on gitter, added a section to 'Troubleshooting' about running locally. Changed the 'Troubleshooting' header so it better stands out and created sub-sections for both 'running locally' and 'ensime'.

Added troubleshooting for running locally, refering to issue #560.

---

DEV_GUIDE.md

This pul request removes the hardcoded version number related to the `sbt-exercises` plugin from the developer guide.
@dialelo Could you take a look please?

Removes hardcoded version number for sbt-exercise plugin in developer guide

---

README.md
app.json
build.sbt

This PR:
* Upgrades the Evaluator client to the latest version
* Updates the `build.sbt` file in order to use runtime dependency as artifact dependency, instead of sbt module dependency.
* Removes the `Running locally` troubleshooting section since the issue has been fixed (issue https://github.com/scala-exercises/scala-exercises/issues/560)
Please, @raulraja could you take a look? Thanks!

JP - Upgrades Evaluator Client

---

server/public/javascripts/emojify-cdn.js

Fixes #467 
This PR modifies a JS script we're using right now to fetch emoji images to add support for HTTP in order to avoid security problems. Right now it seems there are no other conflictive resources being loaded as HTTP. Could you please review, @dialelo? Thanks!! :)

Change resource access from HTTP to HTTPS

---

server/app/org/scalaexercises/exercises/controllers/ApplicationController.scala
server/conf/routes

Based on the code used in the Play Framework website.
Fixes #563.

Remove the trailing slash from a route if no handler is found.

---

client/src/main/scala/scripts/ExercisesJS.scala
client/src/main/scala/utils/DomHandler.scala

Fixes #606 
This PR includes code to fix paste events not being correctly handled by the input fields in the exercises. It also replaces the resizing code, as the resulting size wasn't accurate for long texts.
Could you please review, @dialelo @rafaparadela @juanpedromoreno? Thanks!

Fixing problems with input fields resize on paste events

---

server/app/org/scalaexercises/exercises/controllers/ApplicationController.scala

We're experiencing some issues in production, potentially because of the `play` cache. This PR removes it until we have a fix for that.

Removes play cache when fetching GH info

---

build.sbt
project/plugins.sbt

...  through `sbt-org-policies` plugin.
This change fixes the issue we had yesterday on the index page, in production, when fetching GH info, where users returned by the GH API might be null. Related to https://github.com/47deg/github4s/pull/144 .

Upgrades to the latest version of Github4s

---

compiler/src/main/scala/org/scalaexercises/exercises/compiler/formatting.scala
compiler/src/test/scala/org/scalaexercises/exercises/compiler/CommentRenderingRegressions.scala

This PR fixes the problem with comments being converted to text, first reported in https://github.com/scala-exercises/exercises-stdlib/issues/50
Section in [Parent Classes](https://www.scala-exercises.org/std_lib/parent_classes) before:
Section in [Parent Classes](https://www.scala-exercises.org/std_lib/parent_classes) after:
Section in [Type Variance](https://www.scala-exercises.org/std_lib/type_variance) before:
Section in [Type Variance](https://www.scala-exercises.org/std_lib/type_variance) after:
Note: When debugging this problem I realised it might be an issue with scala-ide/scalariform. Since [they're not planning to make any new releases](https://github.com/scala-ide/scalariform/issues/235#issuecomment-288540527) I found this workaround. The previous code was assuming that two …

Fix comment rendering

---

server/app/views/templates/library/index.scala.html

I was checking the bug reported by @AdrianRaFo, @kastoestoramadus and @AntonioMateoGomez  and the problem was in the difference of the files included in footer between home and library layout.
In the library layout we didn't include neither jquery.min.js nor bootstrap.min.js like as home layout.
Adding it, all works fine.
Fixed #658
Fixed #660
Fixed #647

Add jquery and bootstrap.js to library layout (#658)

---

server/app/assets/stylesheets/layout/_exercises.scss
server/app/assets/stylesheets/libraries/_functions.scss

* Use one step animation, instead of a linear one, so we avoid repainting continuously
* Add will-change property as is the actual way on informing the browser that an element will not stay the same
* Add also null 3D transform to lay the CPU burden down, as IE or Edge doesn't have will-change implemented as of yet

Change exercises input animation method

---

compiler/src/main/scala/org/scalaexercises/exercises/compiler/MethodBodyReader.scala
compiler/src/test/scala/org/scalaexercises/exercises/compiler/MethodBodyReaderSpec.scala

When a block starts with a value that uses the `(a b c)` syntax sugar for `a.b(c)`, the leading `(` is stripped.
Two examples of this are:
- [Applicative composition](https://www.scala-exercises.org/cats/applicative) in the cats exercises
```scala
Applicative[List] compose Applicative[Option]).pure(1) ...
```
- [Lens composition](https://www.scala-exercises.org/monocle/lens) in the monocle exercises.
```scala
addressLens composeLens streetNumber).get(john) ...
```
I wanted to keep the unit test simple and not worry about imports, so I used composition of the List.apply method for indexing.
I struggled a bit to figure out how to version everything with the plugins in place to be able to test this running scala-exercises locally. Ivy wasn't pulling in my locally published snapshots and …

Better handle syntax sugar for compose examples

---

client/src/main/scala/Effects.scala

Fixes: https://github.com/scala-exercises/exercises-cats/issues/65
This PR tries to fix an issue related to how we handle user progress in the application. In some circumstances an user can have progress stored for an exercise and when coming back to it later this exercise can be changed. If the exercise has less fields than before (i.e.: it's been splitted into two), these extra stored values will still be sent to the external compiler and any evaluation will be rejected for carrying extra parameters for the exercise function.
What this code does is simply verifying the state just after retrieval, to check if we're storing more values than those actually required, and if that's the case invalidating the progress for that exercise in particular (which in my opinion should be desirable, as …

Validating user progress regarding exercises subject to change

---

server/app/assets/stylesheets/layout/_exercises.scss

This change will make block with error log expand to fill whole message.
Before:
After:

Expand error log area to fill all content

---

.scala-steward.conf

Because it needs to update some environment variables in the platform side.

Ignores Newrelic for Scala-Steward

---

server/app/views/templates/home/index.scala.html

* Remove Google Plus link from the list of shareable services.
This fixes #707

Remove Google Plus from index.scala.html template
