scala-exercises/scala-exercises

app/json/caseclasses.json

Missing Person case class definition and default value definition to answer the exercises

Person case class definition

---

app/json/implicits.json

The question has multiple valid answers, this proposal has multiple questions with only one correct answer and is shows better how Scala implicit conversion works.
I was unable to setup all the grunt stuff to test it properly, hope it's ok.

Implicits multiple solutions

---

app/json/tuples.json

I thought it might be useful to show an example where a tuple can be quickly assigned to multiple variables, i.e.
val student = ("Sean Rogers", 21, 3.5)
val (name, age, gpa) = student

adding assignment example for tuples

---

app/json/caseclasses.json

Case classes are Serializable.
btw, with koans generator is slightly easier :P

case classes are serializable

---

app/json/forexpressions.json

An example on how for can be translated to flatMap, map and filter

For translates to flatMap, map & filter

---

app/json/maps.json

Insists on the fact that the Map is immutable

Maps - Immutability

---

app/json/sets.json

Added the comment that you can also sum elements in a Set with 
mySet.sum

Added comment mySet.sum

---

app/json/options.json

add collection style operations like map and fold to options

add collection style operations to options

---

app/json/parentclasses.json

Your koans serve me as a scala reference. I want to see them working and updated. Error reminded me about catch22 so I changed example a bit, I hope you like it.

Parent classes koan fix

---

app/json/traversables.json

This PR contains a few grammar and exercises fixes around the 'Traversables' exercises.

Traversables typos

---

.gitignore
.travis.yml
build.sbt

Issue #61 
Actually it only compiles the code because the tests need a database. We can add a new ticket in a future to add the tests execution in the CI
Please @rafaparadela could you review? Thanks!

Add continuous integration

---

build.sbt
project/plugins.sbt
scala-exercises-client/src/main/scala/common/ExtAjax.scala
scala-exercises-client/src/main/scala/common/Framework.scala
scala-exercises-client/src/main/scala/example/ExampleJS.scala
scala-exercises-client/src/test/scala/example/ScalaJSExampleSpec.scala
scala-exercises-content/src/main/scala/exercises/stdlib/Extractors.scala
scala-exercises-content/src/main/scala/exercises/stdlib/package.scala
scala-exercises-server/app/Global.scala
scala-exercises-server/app/config/Routes.scala
scala-exercises-server/app/controllers/Application.scala
scala-exercises-server/app/controllers/ExercisesController.scala
scala-exercises-server/app/controllers/JsonFormats.scala
scala-exercises-server/app/controllers/UserController.scala
scala-exercises-server/app/controllers/package.scala
scala-exercises-server/app/models/Metadata.scala
scala-exercises-server/app/models/UserModel.scala
scala-exercises-server/app/services/UserServices.scala
scala-exercises-server/app/services/messages/User.scala
scala-exercises-server/app/services/parser/ExercisecodeExtractor.scala
scala-exercises-server/app/services/parser/ExercisesService.scala
scala-exercises-server/app/utils/OAuth2.scala
scala-exercises-server/app/utils/StringUtils.scala
scala-exercises-server/test/ApplicationSpec.scala
scala-exercises-server/test/ExercisesServiceSpec.scala
scala-exercises-server/test/IntegrationSpec.scala

This would close #60.
Needs to be rebased after changes from #82 are taken care of.

Add sbt-scalariform

---

build.sbt
project/activator-sbt-echo-shim.sbt
project/activator-sbt-eclipse-shim.sbt
project/activator-sbt-idea-shim.sbt

Some preliminary build file cleanup. More to come, but probably not until way down the road when it's worth the effort.

Build file cleanup

---

app/json/options.json

val number: Option[Int] = Some(3)
val result1 = number.map(_ * 1.5) // The type of result1 is now Option[Double]

It may be interessting to precise the type of result1

---

scala-exercises-content/src/main/scala/exercises/stdlib/Classes.scala
scala-exercises-content/src/main/scala/exercises/stdlib/Extractors.scala
scala-exercises-content/src/main/scala/exercises/stdlib/LiteralBooleans.scala
scala-exercises-content/src/main/scala/exercises/stdlib/package.scala
scala-exercises-server/app/assets/stylesheets/layout/_exercises.scss
scala-exercises-server/app/assets/stylesheets/layout/_sidebar.scss
scala-exercises-server/app/assets/stylesheets/modules/_code.scss
scala-exercises-server/app/controllers/Application.scala
scala-exercises-server/app/models/Metadata.scala
scala-exercises-server/app/services/parser/ExercisecodeExtractor.scala
scala-exercises-server/app/views/templates/category.scala.html
scala-exercises-server/app/views/templates/exercise.scala.html
scala-exercises-server/app/views/templates/exercises.scala.html
scala-exercises-server/app/views/templates/progress.scala.html
scala-exercises-server/app/views/templates/section.scala.html
scala-exercises-server/conf/routes

This PR adds several changes at:
- **GET /:section** Goes to the first category of the section e.g.: *http://localhost:9000/stdlib*
- **GET /:section/:category** Goes to this category of the section e.g.: *http://localhost:9000/stdlib/Extractors*
- **Section**: Now includes the property `color: String`
- **Exercise**: Now includes the property `explanation: Option[String]` (*Some exercises includes a clarification after the question, to improve the understanding of the concept.*)
- **Exercises**: The list of exercises of a particular category (*[screenshot](http://rafp.es/1QUVAH2)*)
- **Progress Bar**: Reusable progress bar to be shown at [home](http://rafp.es/1QUZn7l) and at the Exercises page.
- Ability to detect code blocks at [category description](http://rafp.es/1kmyPxb), at exercise …

Exercises page

---

build.sbt
scala-exercises-content/src/main/exercises/exercises/stdlib/Classes.scala
scala-exercises-content/src/main/exercises/exercises/stdlib/Extractors.scala
scala-exercises-content/src/main/exercises/exercises/stdlib/LiteralBooleans.scala
scala-exercises-content/src/main/exercises/exercises/stdlib/package.scala

This is prep work for the future exercise loading architecture, which may leverage a SBT plugin.

Improve classpath configurations

---

scala-exercises-content/src/main/exercises/exercises/stdlib/Extractors.scala

This clears some warnings in the Extractors file.
@noelmarkham can you please review? thanks

Fixes warnings related to tuples & Unapply

---

app/json/partialfunctions.json

You don't have to specify type of the argument multiple times

---

site/client/src/main/scala/Actions.scala
site/client/src/main/scala/Api.scala
site/client/src/main/scala/Effects.scala
site/client/src/main/scala/Model.scala
site/client/src/main/scala/State.scala
site/client/src/main/scala/Ui.scala
site/client/src/main/scala/messages/Exercises.scala
site/client/src/main/scala/scripts/ExercisesJS.scala
site/client/src/main/scala/utils/DomHandler.scala
site/content/src/main/exercises/exercises/stdlib/LiteralBooleans.scala
site/server/app/assets/stylesheets/layout/_exercises.scss
site/server/app/assets/stylesheets/libraries/_functions.scss
site/server/app/assets/stylesheets/libraries/_variables.scss
site/server/app/assets/stylesheets/modules/_code.scss
site/server/app/views/templates/library/exercise.scala.html

Some of the changes included in this PR are:
- The `onKeyUp` event expects now two different effects; the second one for enter-key pressed, which triggers an action to compile the exercise.
- Added the condition to compile just if the exercise is filled.
- Added visual effects for user interaction as: colours of the inputs, visibility of the compile button, opacity of the ribbon,  height of the compiling message wrapper, etc.
- Has been changed the logic to update the UI, based on the class attribute of the exercise node.
@dialelo @raulraja Could you review please? Thank you.

Enriched state-effects-ui

---

site/client/src/main/scala/Actions.scala
site/client/src/main/scala/Api.scala
site/client/src/main/scala/Effects.scala
site/client/src/main/scala/Model.scala
site/client/src/main/scala/State.scala
site/client/src/main/scala/Ui.scala
site/client/src/main/scala/common/ExtAjax.scala
site/client/src/main/scala/messages/Exercises.scala
site/client/src/main/scala/scripts/ExercisesJS.scala
site/client/src/main/scala/utils/DomHandler.scala
site/client/src/test/scala/Factories.scala
site/client/src/test/scala/ModelSpec.scala
site/client/src/test/scala/ProgramSpec.scala
site/client/src/test/scala/StateSpec.scala
site/server/app/assets/stylesheets/layout/_exercises.scss
site/server/app/assets/stylesheets/libraries/_functions.scss
site/server/app/assets/stylesheets/libraries/_variables.scss
site/server/app/assets/stylesheets/modules/_code.scss
site/server/app/views/templates/library/exercise.scala.html
site/server/app/views/templates/library/index.scala.html

This PR organizes the client-side program around first-class
actions. Actions represent what can happen in the system, and
they can have different outcomes. We may want to update the state
of the world responding to certain action, update the UI as a side
effect, or perform an effect (for example AJAX communication) that
may result in further actions.
I've given a explicit type to the state of the application, for now
it's just a type alias. At any given time, the program has a certain
state. Whenever an action occurs, a reducing function with the signature
`(s: State, a: Action): State` yields the new state.
Since the program state changes over time, it is stored in a reactive
variable.
Since the UI is rendered by the server and the client updates it to
reflect the current state, I've …

Organize the client-side logic around actions

---

site/server/app/views/templates/library/index.scala.html
site/server/app/views/templates/library/sectionRow.scala.html

Highlight active section with section's color

---

site/build.sbt
site/server/app/com/fortysevendeg/exercises/services/ExercisesService.scala
site/server/app/services/exerciseV0/BooleanTypeConversion.scala
site/server/test/TypeConversionSpec.scala

Coerce only "true" and "false" strings to booleans

---

site/server/app/assets/stylesheets/layout/_books-docs.scss
site/server/app/views/templates/home/index.scala.html
site/server/app/views/templates/library/index.scala.html

This PR removes symbolset icons.
Resolves: #138 
@juanpedromoreno @dialelo Good to merge?

Added FontAwesome icons instead of Symbolset resources

---

.travis.yml
scripts/create_db
scripts/create_test_db
site/build.sbt
site/client/src/main/scala/utils/DomHandler.scala
site/client/src/test/scala/ModelSpec.scala
site/server/test/ExercisesServiceSpec.scala
site/server/test/UserStoreSpec.scala

- Switch to old Travis infrastructure and disable forking in tests since there are [known issues](https://github.com/travis-ci/travis-ci/issues/3775) with such options in Travis CI.
- Disable `ExerciseServiceSpec` failing tests due to the overhaul of the library compiler.
- Run ScalaCheck tests with ScalaTest instead of specs2, since failures with specs2 don't make the build fail, this is likely an issue in specs2.

Run and pass tests in ci

---

core/compiler/src/main/scala/com/fortysevendeg/exercises/compiler/MethodBodyReader.scala
core/compiler/src/main/scala/com/fortysevendeg/exercises/compiler/SourceTextExtraction.scala
core/sbt-exercise/src/main/scala/com/fortysevendeg/exercises/sbtexercise/ExerciseCompilerPlugin.scala
site/build.sbt

This will include various updates and fixes I'm find as I work through a larger exercise example for the content project.

Compiler updates and fixes

---

site/content/src/main/exercises/foolib/BarSection.scala
site/content/src/main/exercises/foolib/FooSection.scala
site/content/src/main/exercises/foolib/SampleLibrary.scala
site/content/src/main/exercises/stdlib/ClassExercises.scala
site/content/src/main/exercises/stdlib/StdLib.scala
site/content/src/main/scala/foolib/FooBarHelper.scala

Begin to add back exercise content.
A few notes:
- This more clearly demonstrates the compiler and highlights some of the issues that need to be addressed.
- This needs to be merged after #178

Bring back exercise content

---

site/content/src/main/exercises/catslib/CatsLibrary.scala
site/content/src/main/exercises/catslib/IdentitySection.scala
site/content/src/main/exercises/catslib/XorSection.scala

The `Xor` section is not finished yet but opening this in order to work on compiler issues.
@raulraja take a look please.

A few Cats exercises

---

site/server/app/assets/stylesheets/libraries/_variables.scss
site/server/app/assets/stylesheets/modules/_jumbotron.scss
site/server/app/com/fortysevendeg/exercises/controllers/ExercisesController.scala
site/server/app/com/fortysevendeg/exercises/persistence/repositories/UserProgressRepository.scala
site/server/app/views/templates/home/index.scala.html

@raulraja Could you review this PR please?

Fixed layout header and font size h1 Jumbotron

---

core/compiler/src/main/scala/com/fortysevendeg/exercises/compiler/MethodBodyReader.scala
core/compiler/src/main/scala/com/fortysevendeg/exercises/compiler/SourceTextExtraction.scala
core/compiler/src/test/scala/com/fortysevendeg/exercises/compiler/MethodBodyReaderSpec.scala

This is a fix for method body extractions in the compiler. I've also added some new tests.

Fix method body extraction

---

site/server/app/com/fortysevendeg/exercises/services/ExercisesService.scala

Fix exercise descriptions

---

site/server/test/UserProgressQueriesSpec.scala

This PR provides some additional checks for the user progress queries.
Please, @raulraja @dialelo review at your convenience. Thanks!

JP - User Progress Queries checks

---

site/server/app/com/fortysevendeg/exercises/persistence/domain/UserProgressQueries.scala

Please, @raulraja @dialelo could you review? Thanks!

JP - Provides automatic shapeless derivation from the case class

---

site/server/app/com/fortysevendeg/exercises/persistence/repositories/UserProgressRepository.scala
site/server/app/com/fortysevendeg/exercises/services/free/userprogressops.scala
site/server/test/UserProgressRepositorySpec.scala

Please, @raulraja @dialelo review at your convenience. Thanks.

JP - User Progress by Section new Specs

---

bower.json
site/server/app/assets/stylesheets/layout/_books-docs.scss
site/server/app/assets/stylesheets/layout/_exercises.scss
site/server/app/assets/stylesheets/layout/_footer.scss
site/server/app/assets/stylesheets/layout/_global.scss
site/server/app/assets/stylesheets/layout/_how-it-work.scss
site/server/app/assets/stylesheets/layout/_sidebar.scss
site/server/app/assets/stylesheets/libraries/_mixin.scss
site/server/app/assets/stylesheets/modules/_modals.scss
site/server/app/assets/stylesheets/modules/_navbar.scss
site/server/app/views/templates/home/footer.scala.html
site/server/app/views/templates/home/index.scala.html
site/server/app/views/templates/library/index.scala.html
site/server/app/views/templates/library/sectionRow.scala.html

Isra 214 fixed layout

---

core/compiler/src/main/scala/com/fortysevendeg/exercises/compiler/Compiler.scala
core/compiler/src/main/scala/com/fortysevendeg/exercises/compiler/DocParser.scala
core/compiler/src/main/scala/com/fortysevendeg/exercises/compiler/TreeGen.scala
core/compiler/src/test/scala/com/fortysevendeg/exercises/compiler/TreeGenSpec.scala
core/runtime/src/main/scala/com/fortysevendeg/exercises/MethodEval.scala
core/runtime/src/main/scala/com/fortysevendeg/exercises/model.scala
site/server/app/com/fortysevendeg/exercises/services/ExercisesService.scala

- clean up code
- remove `Option` wrapper on various fields in the runtime model

Various Compiler Updates

---

site/server/app/com/fortysevendeg/exercises/persistence/domain/UserProgressQueries.scala
site/server/app/com/fortysevendeg/exercises/persistence/repositories/UserProgressRepository.scala
site/server/app/com/fortysevendeg/exercises/services/ExercisesService.scala
site/server/app/com/fortysevendeg/exercises/services/free/userprogressops.scala
site/server/test/UserProgressQueriesSpec.scala
site/server/test/UserProgressRepositorySpec.scala
site/shared/src/main/scala/shared/Exercise.scala
site/shared/src/main/scala/shared/User.scala

This PR brings a couple of new services to fetch the user progress.
Please, @rafaparadela @raulraja @dialelo @andyscott Review when you have a chance. 
Thanks.

JP - Overall User Progress and User Progress by Library

---

site/client/src/main/scala/utils/DomHandler.scala

This PR adds a minor change that solves the issue #211 
@dialelo is good to merge? Thanks.

Fix the regular expression for responses replacement

---

site/client/src/main/scala/Actions.scala
site/client/src/main/scala/Api.scala
site/client/src/main/scala/Effects.scala
site/client/src/main/scala/State.scala
site/client/src/main/scala/Ui.scala
site/client/src/main/scala/config/Routes.scala
site/client/src/main/scala/scripts/ExercisesJS.scala
site/client/src/main/scala/utils/DomHandler.scala
site/server/app/assets/stylesheets/layout/_exercises.scss
site/server/app/com/fortysevendeg/exercises/controllers/ApplicationController.scala
site/server/app/views/templates/home/index.scala.html
site/server/app/views/templates/library/index.scala.html
site/server/app/views/templates/widgets/progress.scala.html

Needs an error message when exercise fails due to the user not being authenticated but I think we should leave that for the Github auth issue.

Show a user's exercise progress

---

core/runtime/src/main/scala/com/fortysevendeg/exercises/MethodEval.scala
core/runtime/src/test/scala/com/fortysevendeg/exercises/MethodEvalSpec.scala
site/server/app/com/fortysevendeg/exercises/controllers/ExercisesController.scala
site/server/app/com/fortysevendeg/exercises/services/ExercisesService.scala
site/shared/src/main/scala/shared/Exercise.scala
site/shared/src/main/scala/shared/free/algebra.scala

This initial commit will be broken (in the site project). I will fix it shortly.

Convert eval result to ADT

---

site/server/app/com/fortysevendeg/exercises/persistence/domain/UserQueries.scala
site/server/app/com/fortysevendeg/exercises/persistence/repositories/UserRepository.scala
site/server/app/com/fortysevendeg/exercises/utils/OAuth2.scala
site/server/conf/evolutions/default/1.sql
site/server/test/ArbitraryInstances.scala
site/shared/src/main/scala/shared/User.scala

According to the possibility that an user may not have any defined name, the app should cover this case. This PRs resolves this issue.
@juanpedromoreno @raulraja Is good to merge?

Changes name field as option

---

site/server/app/assets/stylesheets/layout/_how-it-work.scss
site/server/app/views/templates/home/index.scala.html

This PR solves #237 @israelperezglez looks good to you?

Adds effects to the wizard

---

site/server/test/com/fortysevendeg/exercises/persistence/PersistenceModuleSpec.scala
site/server/test/com/fortysevendeg/exercises/persistence/queries/UserProgressQueriesSpec.scala
site/server/test/com/fortysevendeg/exercises/persistence/queries/UserQueriesSpec.scala
site/server/test/com/fortysevendeg/exercises/persistence/repositories/UserProgressRepositorySpec.scala
site/server/test/com/fortysevendeg/exercises/persistence/repositories/UserRepositorySpec.scala
site/server/test/com/fortysevendeg/exercises/services/ExercisesServiceSpec.scala
site/server/test/com/fortysevendeg/exercises/support/ArbitraryInstances.scala
site/server/test/com/fortysevendeg/exercises/support/DatabaseInstance.scala

Please, @rafaparadela @raulraja @dialelo @andyscott review at your convenience.

JP - Organizes Test files in different scala packages

---

site/server/app/views/templates/library/index.scala.html

@rafaparadela take a look please.

Minor fix for avoiding malformed section names in URLs

---

site/server/app/com/fortysevendeg/exercises/controllers/ApplicationController.scala
site/server/app/com/fortysevendeg/exercises/services/free/userprogressops.scala
site/server/app/views/templates/home/index.scala.html
site/server/app/views/templates/home/libraryGridItem.scala.html
site/server/app/views/templates/library/index.scala.html
site/server/app/views/templates/widgets/progress.scala.html
site/shared/src/main/scala/shared/User.scala

Displays a "Start" call to action button when a library hasn't been started or the user is anonymous:
Displays a progress bar with the section progress when the user is logged in:
Take a look @rafaparadela @juanpedromoreno @israelperezglez @raulraja please!

Show overall user progress on the homepage

---

site/content/src/main/exercises/catslib/XorSection.scala

More exercises for the Xor section

---

site/server/app/assets/stylesheets/layout/_books-docs.scss
site/server/app/assets/stylesheets/layout/_exercises.scss
site/server/app/assets/stylesheets/layout/_how-it-work.scss
site/server/app/assets/stylesheets/libraries/_variables.scss
site/server/app/assets/stylesheets/main.scss
site/server/app/assets/stylesheets/modules/_navbar.scss
site/server/app/views/templates/home/index.scala.html
site/server/app/views/templates/library/exercise.scala.html

Review general responsive

---

site/server/app/views/templates/home/libraryGridItem.scala.html

@dialelo @raulraja I've forgotten applying the conversion for librery names at home. Looks good to merge?

Humanize library name

---

site/server/app/views/templates/library/index.scala.html

Review exercises responsive

---

site/client/src/main/scala/scripts/ExercisesJS.scala
site/server/app/views/templates/library/exercise.scala.html

- Disallows tab navigation to the "Run" buttons.
- Tries to compile exercises on blur as it used to
@rafaparadela @israelperezglez please take a look!

Compile exercise on blur

---

README.md

Solves #157 
@dialelo Can you take a look?

Several updates to the Readme

---

site/server/conf/application.conf

@raulraja please take a look and merge.

Change top libraries config to reflect new library names

---

site/content/src/main/exercises/catslib/CatsLibrary.scala
site/content/src/main/exercises/catslib/FunctorSection.scala

Add a section for learning about functors to the Cats exercises

---

site/server/app/assets/stylesheets/layout/_sidebar.scss

Closes #280 
@israelperezglez please review and merge.

Allow scrolling to the bottom of the sidebar

---

site/content/src/main/exercises/catslib/FunctorSection.scala
site/content/src/test/scala/exercises/catslib/FunctorSpec.scala
site/content/src/test/scala/exercises/catslib/IdentitySpec.scala
site/content/src/test/scala/exercises/catslib/XorSpec.scala

This PR tests the cats exercises we currently have. I'm going to work on adding more sections to the cats' library and wanted to tests the existing ones beforehand.

Test cats exercises

---

core/compiler/src/main/scala/com/fortysevendeg/exercises/compiler/Compiler.scala
core/compiler/src/main/scala/com/fortysevendeg/exercises/compiler/SourceTextExtraction.scala
core/compiler/src/main/scala/com/fortysevendeg/exercises/compiler/TreeGen.scala
core/compiler/src/test/scala/com/fortysevendeg/exercises/compiler/SourceTextExtractionSpec.scala
core/compiler/src/test/scala/com/fortysevendeg/exercises/compiler/TreeGenSpec.scala
core/runtime/src/main/scala/com/fortysevendeg/exercises/MethodEval.scala
core/runtime/src/main/scala/com/fortysevendeg/exercises/model.scala
core/runtime/src/test/scala/com/fortysevendeg/exercises/MethodEvalSpec.scala
site/server/app/com/fortysevendeg/exercises/services/ExercisesService.scala

WIP for #259.
This has pushed the compiler code to be a bit messier than I want. Cleanup will come sometime soon, hopefully.

Capture imports for koan style exercises

---

site/client/src/main/scala/Api.scala

Closes #306 
@raulraja take a look please.

Show helpful error message when there are network problems

---

site/server/app/assets/stylesheets/modules/_code.scss
site/server/app/com/fortysevendeg/exercises/services/ExercisesService.scala

Fixed font-size + font family for block of code
@raulraja could you review this PR please?

Fixed text for block of code

---

site/content/src/main/scala/catslib/Applicative.scala
site/content/src/main/scala/catslib/Apply.scala
site/content/src/main/scala/catslib/CatsLibrary.scala
site/content/src/main/scala/catslib/Foldable.scala
site/content/src/main/scala/catslib/Validated.scala

And fix a few markup errors along the way, take a look please @raulraja.

Include new cats sections in site's content

---

site/build.sbt
site/content/src/main/scala/catslib/CatsLibrary.scala
site/content/src/main/scala/catslib/Monad.scala
site/content/src/main/scala/catslib/MonadHelpers.scala
site/content/src/test/scala/exercises/catslib/MonadSpec.scala

@scala-exercises/core-mergers please review, thanks in advance!

Add a monad section to cats exercises

---

site/build.sbt
site/content/src/main/scala/catslib/CatsLibrary.scala
site/content/src/main/scala/catslib/Monoid.scala
site/content/src/test/scala/exercises/catslib/MonoidSpec.scala

Please review @scala-exercises/core-mergers.

Add Monoid section to cats library

---

site/content/src/main/scala/catslib/CatsLibrary.scala
site/content/src/main/scala/catslib/Traverse.scala
site/content/src/main/scala/catslib/TraverseHelpers.scala
site/content/src/test/scala/exercises/catslib/TraverseSpec.scala

Please take a look @scala-exercises/core-mergers.

Add Traverse section to cats library

---

site/build.sbt
site/content/src/main/scala/catslib/CatsLibrary.scala
site/content/src/main/scala/catslib/Semigroup.scala
site/content/src/test/scala/exercises/catslib/SemigroupSpec.scala

@scala-exercises/core-mergers take a look please!

Add Semigroup section to cats exercises

---

core/compiler/src/main/scala/com/fortysevendeg/exercises/compiler/SourceTextExtraction.scala
core/compiler/src/test/scala/com/fortysevendeg/exercises/compiler/SourceTextExtractionSpec.scala

This fixes one bug I found with import statement generation.
I haven't finished all the changes for this. Please do not merge it... yet.

Fix import bugs

---

site/server/app/assets/stylesheets/modules/_code.scss

@raulraja could you review this PR please?

Fixed text code

---

site/content/src/main/scala/stdlib/Objects.scala

Small improvements of text for lesson "Objects".

Small improvements of text for lesson "Objects".

---

server/app/com/fortysevendeg/exercises/services/ExercisesService.scala

This PR:
- Get Play `classLoader` if exists
- Get runtime libraries lazily.
@dialelo Can you review please?

Select other classLoader

---

runtime/src/main/scala/com/fortysevendeg/exercises/Exercises.scala

This PR adds a mechanism to get classes from several classLoaders.
@dialelo Could you review please? Thank you.

Added a loop to get classes from several classLoaders

---

Procfile
build.sbt
common/BuildCommon.scala
project/plugins.sbt
sbt-exercise/src/sbt-test/sbt-exercise/basic/project/plugins.sbt
sbt-exercise/src/sbt-test/sbt-exercise/scalariform/project/plugins.sbt

This PR adds setting for distribution of projects on Sonatype.
@dialelo @raulraja Could you take a look please? Thank you.

Adds settings for distributing projects in Sonatype

---

.buildpacks
Gemfile
Gemfile.lock
Procfile
app.json

After a lot of PoC... This PR includes required settings to deploy `site` on Heroku:
Due to we need `sass`, I should add:
- Adds `Gemfile` to install `sass`.
- Set multiple buildpack:  `https://github.com/heroku/heroku-buildpack-multi.git` 
- Add buildpacks: Ruby and Scala
@dialelo @raulraja Could you review please? Thank you.

Added deployment settings

---

client/src/main/scala/Effects.scala
client/src/main/scala/Model.scala
client/src/main/scala/State.scala
client/src/main/scala/Ui.scala
client/src/main/scala/common/ExtAjax.scala
client/src/main/scala/messages/Exercises.scala
client/src/main/scala/utils/DomHandler.scala
server/app/com/fortysevendeg/exercises/ApplicationLoader.scala
server/app/com/fortysevendeg/exercises/controllers/ApplicationController.scala
server/app/com/fortysevendeg/exercises/controllers/AuthenticationModule.scala
server/app/com/fortysevendeg/exercises/controllers/ExercisesController.scala
server/app/com/fortysevendeg/exercises/controllers/UserController.scala
server/app/com/fortysevendeg/exercises/controllers/UserProgressController.scala
server/app/com/fortysevendeg/exercises/persistence/PersistenceModule.scala
server/app/com/fortysevendeg/exercises/persistence/domain/UserProgressQueries.scala
server/app/com/fortysevendeg/exercises/persistence/domain/UserQueries.scala
server/app/com/fortysevendeg/exercises/persistence/repositories/UserProgressRepository.scala
server/app/com/fortysevendeg/exercises/services/free/TaskOps.scala
server/app/com/fortysevendeg/exercises/services/free/dbops.scala
server/app/com/fortysevendeg/exercises/services/free/userops.scala
server/app/com/fortysevendeg/exercises/services/free/userprogressops.scala
server/app/com/fortysevendeg/exercises/services/interpreters/interpreters.scala
server/app/com/fortysevendeg/exercises/services/messages/User.scala
server/app/com/fortysevendeg/exercises/utils/OAuth2.scala
shared/src/main/scala/shared/Exercise.scala
shared/src/main/scala/shared/Progress.scala
shared/src/main/scala/shared/User.scala
shared/src/main/scala/shared/free/algebra.scala

The following PR allows `Free` expressions to run to `Future` avoiding `Task#attemptRun` and running in Task async mode registering a shameful promise callback.
@dialelo @rafaparadela Please review, thanks!

Non-blocking controllers running Free straight to Future

---

server/app/com/fortysevendeg/exercises/services/ExercisesService.scala
server/test/com/fortysevendeg/exercises/services/ExercisesServiceSpec.scala

@rafaparadela @raulraja take a look please.

Fix ExerciseService spec

---

app.json
server/app/com/fortysevendeg/exercises/ApplicationLoader.scala
server/conf/application.conf

This PR enables a better config to have review apps working in heroku.
https://scala-exercises-pr-378.herokuapp.com/
@rafaparadela @dialelo Can you please review? thanks!

Propagate app config to Heroku Review Apps

---

server/app/com/fortysevendeg/exercises/ApplicationLoader.scala
server/app/com/fortysevendeg/exercises/controllers/LoaderIOController.scala
server/conf/application.conf
server/conf/routes

@rafaparadela @dialelo Can you please review?

Loader.io provisioning

---

server/conf/routes

Routes fix because loader IO requires a dangling /

---

server/app/com/fortysevendeg/exercises/controllers/ApplicationController.scala

@raulraja @rafaparadela plz take a look.

Distinguish between not found libraries, sections and server errors

---

server/conf/application.conf

Added new database env var

---

README.md

Addresses #169 
@dialelo @rafaparadela Please review. Thanks!

Code of Conduct and Contributing section

---

build.sbt
common/BuildCommon.scala
common/Dependencies.scala
compiler/src/test/scala/com/fortysevendeg/exercises/compiler/CommentRenderingRegressions.scala
project/plugins.sbt
runtime/src/main/scala/com/fortysevendeg/exercises/MethodEval.scala

Add Scalatest runtime dependency to the server

---

client/src/main/scala/scripts/ExercisesJS.scala
client/src/main/scala/utils/DomHandler.scala

@raulraja @rafaparadela plz take a look.

Don't run exercise on blur

---

client/src/main/scala/utils/DomHandler.scala

@raulraja @rafaparadela plz take a look.

Only emojify modal dialogs

---

app.json
build.sbt
server/conf/newrelic.yml

@dialelo Since I have to test this directly in the prod heroku app this may take multiple reviews. Just a heads up. thanks.

Enable New Relic

---

server/app/com/fortysevendeg/exercises/controllers/ApplicationController.scala

Exhaustive pattern matches

---

server/app/com/fortysevendeg/exercises/controllers/ApplicationController.scala
server/app/com/fortysevendeg/exercises/persistence/domain/UserProgressQueries.scala
server/app/com/fortysevendeg/exercises/persistence/repositories/UserProgressRepository.scala
server/app/com/fortysevendeg/exercises/services/free/userprogressops.scala
server/app/com/fortysevendeg/exercises/services/interpreters/interpreters.scala
server/conf/evolutions/default/3.sql
server/test/com/fortysevendeg/exercises/persistence/queries/UserProgressQueriesSpec.scala

Addresses #410. I don't currently check if the last seen section is completed so it will show completed sections anyway. I think it makes more sense and won't confuse users.
When we implement the dialog that takes you to the next section after the current is finished, a user revisiting the last seen section will be prompted to go the next if such section is completed. So I think is OK to take you to the last seen section regardless if is completed, thoughts @raulraja ?

Go to last seen section when visiting a library

---

compiler/src/main/scala/com/fortysevendeg/exercises/compiler/Compiler.scala
compiler/src/test/scala/com/fortysevendeg/exercises/compiler/SourceTextExtractionSpec.scala

@raulraja take a look, should fix the build.

Don't fetch contributions for sections without path

---

server/app/views/templates/base/footerLinks.scala.html
server/app/views/templates/home/footer.scala.html
server/app/views/templates/home/index.scala.html

Fixes #423 
@dialelo @rafaparadela Can you please review?

Added footer links

---

server/app/views/templates/home/index.scala.html
server/app/views/templates/library/index.scala.html
server/app/views/templates/widgets/ga.scala.html

Fixes #424 
@dialelo @rafaparadela This is the same GA tracker as it was in v1

GA tracker

---

build.sbt
error_pages/error.html
server/app/Global.scala
server/app/com/fortysevendeg/exercises/Actions.scala
server/app/com/fortysevendeg/exercises/controllers/ApplicationController.scala
server/app/com/fortysevendeg/exercises/controllers/AuthenticationModule.scala
server/app/com/fortysevendeg/exercises/controllers/LoaderIOController.scala
server/app/com/fortysevendeg/exercises/controllers/OAuthController.scala
server/app/com/fortysevendeg/exercises/controllers/UserController.scala
server/conf/routes

@raulraja @rafaparadela please take a look.

Force HTTPS in production

---

server/app/com/fortysevendeg/exercises/persistence/domain/UserProgressQueries.scala

Limit the last seen section results to 1

---

.travis.yml
build.sbt
sbt-exercise/src/sbt-test/sbt-exercise/basic/build.sbt
sbt-exercise/src/sbt-test/sbt-exercise/basic/content/src/main/scala/SampleLibrary.scala
sbt-exercise/src/sbt-test/sbt-exercise/basic/test
sbt-exercise/src/sbt-test/sbt-exercise/scalariform/test

- Fix the scripted tests for the plugin project
- Re-enable automatic running of scripted by Travis

Fix scripted tests for the plugin project

---

app.json
server/app/com/fortysevendeg/exercises/Actions.scala

@dialelo Please review, thanks!

Enforce use of www

---

README.md

Added live site link to README as the current documentation almost hints you have to run the whole thing on your own to use it.
@dialelo Can you please review?

Add online link

---

server/app/com/fortysevendeg/exercises/ApplicationLoader.scala
server/app/com/fortysevendeg/exercises/controllers/SitemapController.scala
server/app/views/templates/sitemap/sitemap.scala.xml
server/conf/routes

Fixes #442 
@dialelo Can you please review? thanks!

sitemap.xml listing all libs and sections

---

server/app/views/templates/home/index.scala.html

@dialelo Can you please review? thanks!

Fixes broken links pointing to 47deg org

---

server/app/assets/stylesheets/modules/_progress-bars.scss

@dialelo could you review this PR please?
I fixed min-width progress bar.

Fixed min-width progress bar

---

server/app/assets/stylesheets/layout/_exercises.scss

@dialelo @raulraja could you review, please?
This PR changes the input background in the exercises.

Change background input

---

project/build.properties
project/plugins.sbt

@dialelo Can you please review. Let's wait until the preview app is deployed before merging since locally I experienced libs not showing up.

Upgrade to Play 2.4.8 to fix XSS vulnerability

---

build.sbt
sbt-exercise/src/sbt-test/sbt-exercise/basic/build.sbt
sbt-exercise/src/sbt-test/sbt-exercise/scalariform/build.sbt

Make sbt-exercise plugin tests pass again

---

server/app/com/fortysevendeg/exercises/ApplicationLoader.scala
server/app/com/fortysevendeg/exercises/controllers/ApplicationController.scala

Fixes #475 
@dialelo Can you take a look?

Cache the repo stars, watchers and forks for 30 mins

---

server/app/com/fortysevendeg/exercises/Actions.scala

Attempt to debug redirect loop

---

server/app/com/fortysevendeg/exercises/Actions.scala

Looks into the x-forward-proto headers to determine if https since behind the Heroku load balancer request.secure returns false.
@dialelo Can you review? thanks!

Redirect loop fix

---

server/app/com/fortysevendeg/exercises/utils/OAuth2.scala
server/conf/application.dev.conf

Compute callback URL based on the root URL of the site

---

server/app/assets/stylesheets/layout/_exercises.scss
server/app/assets/stylesheets/libraries/_mixin.scss
server/app/assets/stylesheets/modules/_navbar.scss

@dialelo @raulraja could you review please?
- We delete the border-bottom for input solved
- We change all style for menu exercises in mobile

Input solved and fixed sidebar menu in mobile

---

server/app/com/fortysevendeg/exercises/controllers/ApplicationController.scala

This pull request closes #507. It solves the found bug  when the last seen section was renamed or removed.
@dialelo @raulraja Could you take a look when you have a chance? Thanks

Fixes bug when the last seen section was renamed or removed

---

README.md

Just a simple addition to the troubleshooting section in the README, to troubleshoot some problems users may have while creating the PostgreSQL DB and user if using a MacOS X. Could you please review, @franciscodr?

Added troubleshooting section for problems while setting PostgreSQL DB on MacOSX

---

build.sbt

Closes #518 
@jdesiloniz @juanpedromoreno can you confirm that fixes the issue for you? Thanks in advance!

Depend on runtime through library dependency instead of sbt

---

runtime/src/main/scala/org/scalaexercises/exercises/Evaluator.scala
runtime/src/test/scala/com/fortysevendeg/exercises/MethodEvalSpec.scala

@raulraja @dialelo Please, could you review this temporary patch?
Thanks.

Synchronizes code evaluation

---

client/src/main/scala/Model.scala
client/src/main/scala/scripts/ExercisesJS.scala
client/src/test/scala/ModelSpec.scala

Closes #459
@raulraja please take a look.

Allow evaluation of exercises even after being solved

---

runtime/src/main/scala/org/scalaexercises/exercises/MethodEval.scala

Please, @raulraja Review this change at your convenience.
Thanks.

Creates different evaluator instances each time

---

client/src/main/scala/Api.scala

@raulraja @juanpedromoreno please take a look.
Closes #535

Display a friendly error message on server crashes

---

server/app/org/scalaexercises/exercises/controllers/UserProgressController.scala
server/conf/evolutions/default/4.sql

Fixes https://github.com/scala-exercises/scala-exercises/issues/534
Please, @dialelo @raulraja could you review? Thanks!

Provides DB indexes for userProgress table

---

runtime/src/main/scala/org/scalaexercises/exercises/Evaluator.scala
runtime/src/test/scala/com/fortysevendeg/exercises/ExampleTarget.scala
runtime/src/test/scala/com/fortysevendeg/exercises/MethodEvalSpec.scala

@raulraja @juanpedromoreno please take a look.

Capture non fatal errors in exercise evaluation

---

client/src/main/scala/Api.scala

Correctly display user errors

---

build.sbt
runtime/src/main/scala/org/scalaexercises/exercises/Evaluator.scala
runtime/src/test/scala/com/fortysevendeg/exercises/EvaluatorSpec.scala
server/app/org/scalaexercises/exercises/controllers/ExercisesController.scala

Solved #540 
@raulraja please take a look.

Evaluate code with the configured timeout

---

server/app/org/scalaexercises/exercises/services/ExercisesService.scala

Don't show exception message when an exercise throws

---

README.md

Please, @raulraja @dialelo could you review?
Thanks!

Updates Gitter URL

---

build.sbt
definitions/src/main/scala/org/scalaexercises/Test.scala

Fixes #510 
Please, @dialelo @raulraja could you review?
Thanks!

JP - SE-510 DRY Test.scala

---

server/app/org/scalaexercises/exercises/Actions.scala

@dialelo @juanpedromoreno Can you please review? thanks!

Removed println statements

---

DEV_GUIDE.md
README.md

Fixes #120.
This PR is a joint effort with @juanpedromoreno, and includes a first version of the development guide focused on the creation of new contents for Scala Exercises.
Please @raulraja @dialelo could you please review?

First draft of the developer guide

---

DEV_GUIDE.md
compiler/src/main/scala/org/scalaexercises/exercises/compiler/SourceTextExtraction.scala
compiler/src/test/scala/org/scalaexercises/exercises/compiler/SourceTextExtractionSpec.scala
sbt-exercise/src/sbt-test/sbt-exercise/basic/build.sbt
sbt-exercise/src/sbt-test/sbt-exercise/basic/contentinpackages/src/main/scala/org/my/nested/pack/BarSection.scala
sbt-exercise/src/sbt-test/sbt-exercise/basic/contentinpackages/src/main/scala/org/my/nested/pack/FooBarHelper.scala
sbt-exercise/src/sbt-test/sbt-exercise/basic/contentinpackages/src/main/scala/org/my/nested/pack/FooSection.scala
sbt-exercise/src/sbt-test/sbt-exercise/basic/contentinpackages/src/main/scala/org/my/nested/pack/MyLibrary.scala
sbt-exercise/src/sbt-test/sbt-exercise/basic/test

Fixes https://github.com/scala-exercises/scala-exercises/issues/554
Please, @raulraja @dialelo could you review? Thanks.

JP - Allows multi-level deep packages when defining libraries

---

server/app/assets/stylesheets/layout/_technologies.scss
server/app/views/templates/home/index.scala.html

Please @raulraja, can you review it?
I think that that design its pretty awesome to do a call to action to new committers and contributors :-)

Jorgegalindo se 506 add new call to action

---

.travis.yml
README.md
build.sbt
project/plugins.sbt

This PR adds support for code test coverage through codecov.io. Could you please review, @raulraja @dialelo? Thanks a lot!

Add codecov.io support for test coverage

---

app.json

This PR ensures that evaluator environment variables are copied for the deployment associated to each new PR.
Please, @raulraja @dialelo could you review? Thanks!

JP - Inherits the evaluator env vars from production

---

build.sbt
compiler/src/main/scala/org/scalaexercises/exercises/compiler/Compiler.scala

Fixes https://github.com/scala-exercises/scala-exercises/issues/576
Please, @raulraja review at your convenience. Thanks.

JP - Removes transitive dependencies from the meta information

---

README.md

Please, @jdesiloniz could you review it? Thanks!
CC @raulraja

Only takes into account the master branch

---

compiler/src/main/scala/org/scalaexercises/exercises/compiler/Compiler.scala
runtime/src/main/scala/org/scalaexercises/exercises/Exercises.scala
sbt-exercise/src/main/scala/org/scalaexercises/exercises/sbtexercise/ExerciseCompilerPlugin.scala
server/app/org/scalaexercises/exercises/services/ExercisesService.scala

While I played around with the code to familiarize myself with the project, I tried to clean up some small things.
-

Some cleanups (?)

---

server/app/views/templates/base/head.scala.html

Add the canonical url to every page.

---

app.json

This new java opts configuration reduces the memory pressure and improves the general performance.
Please, @raulraja could you review? Thanks!

Fixes Memory issues on Heroku

---

core/src/main/scala/org/scalaexercises/algebra/progress.scala

I created a few helper methods and I replaced
- `FM.sequence( xs.map { ... } )`  with `xs.traverse`,
- some for comprehensions with a simple `map` and
- the pattern `maybeLibrary.fold(Nil: List[Sections])(_.sections)` with `maybeLibrary.foldMap(_.sections)`.

Refactor methods in UserProgressOps

---

server/app/org/scalaexercises/exercises/controllers/ApplicationController.scala
server/app/org/scalaexercises/exercises/controllers/LoaderIOController.scala
server/app/org/scalaexercises/exercises/persistence/PersistenceModule.scala
server/app/org/scalaexercises/exercises/persistence/domain/UserProgressQueries.scala
server/app/org/scalaexercises/exercises/persistence/domain/UserQueries.scala
server/app/org/scalaexercises/exercises/persistence/domain/package.scala
server/app/org/scalaexercises/exercises/services/ExercisesService.scala
server/app/org/scalaexercises/exercises/services/interpreters/interpreters.scala
server/app/org/scalaexercises/exercises/utils/ConfigUtils.scala
server/test/org/scalaexercises/exercises/persistence/PersistenceModuleSpec.scala
server/test/org/scalaexercises/exercises/persistence/domain/FieldNamesSpec.scala
server/test/org/scalaexercises/exercises/persistence/repositories/UserProgressRepositorySpec.scala
server/test/org/scalaexercises/exercises/persistence/repositories/UserRepositorySpec.scala
server/test/org/scalaexercises/exercises/support/ArbitraryInstances.scala

While working on how to work with Doobie transactions with multiple free algebras and how this could be implemented in Scala Exercises, I did some refactoring.
Sorry for this is big, messy PR, which should probably have been multiple separate PRs. The commit messages should give a good indication, so it might help to look at the individual commits when reviewing.

Some refactorings

---

README.md

Relative of the project directory, the conf file is at `server/conf/application.dev.conf`

Update path to application.dev.conf in README

---

build.sbt
server/conf/application.conf

Fixes #603 and #616 
Well-known issue that we should address in a separate PR: https://github.com/scala-exercises/scala-exercises/issues/619

Adds scala-tutorial Library - RE

---

build.sbt
project/ProjectPlugin.scala
server/conf/application.conf

Fixes https://github.com/scala-exercises/scala-exercises/issues/500
Fixes https://github.com/scala-exercises/scala-exercises/issues/497
Fixes https://github.com/scala-exercises/scala-exercises/issues/620
It includes libraries Circe, Monocle and Fetch.

Adds Circe, Fetch and Monocle Libraries

---

server/app/org/scalaexercises/exercises/ApplicationLoader.scala

Attempt to troubleshoot prod issues that we can't reproduce locally.
In prod after a few mins the index seems to through an uncaught exception that we can hopefully see in the logs once this is deployed.

Add debug error handler

---

.travis.yml
project/ProjectPlugin.scala
project/plugins.sbt
server/conf/application.dev.conf

This PR updates the scala versions to 2.11.11 and 2.12.3 , sbt-org-policies to 0.5.12 and all the scala-exercises libraries to their last version
@juanpedromoreno could you please review?
Thanks!

Updating libraries versions

---

project/ProjectPlugin.scala
server/app/org/scalaexercises/exercises/controllers/ExercisesController.scala

This PR modifies the EvalResponse to take into account the consoleOutput
@juanpedromoreno could you please review this?
Thanks!

Including console output in EvalResponse

---

server/app/views/templates/home/index.scala.html
server/app/views/templates/library/exercise.scala.html
server/app/views/templates/library/index.scala.html

Added a 'provisional' alert to remember users must log in before running the exercises

Added an alert

---

.travis.yml

Updating to OpenJDK, to avoid broken compilations in PRs reviews, etc.

Updating JDK version for travis

---

build.sbt
core/shared/src/main/scala/org/scalaexercises/algebra/app.scala
core/shared/src/main/scala/org/scalaexercises/algebra/exercises.scala
core/shared/src/main/scala/org/scalaexercises/algebra/github.scala
core/shared/src/main/scala/org/scalaexercises/algebra/progress/exerciseProgress.scala
core/shared/src/main/scala/org/scalaexercises/algebra/progress/progress.scala
core/shared/src/main/scala/org/scalaexercises/algebra/user.scala
core/shared/src/main/scala/org/scalaexercises/types/exercises.scala

This PR converts the old Free algebra to a Tagless-Final algebra. In consequence, some libraries have been removed from build.sbt. The PR has no changes in other modules so the rest maybe won't compile.

Core module update

---

build.sbt
compiler/src/main/scala/org/scalaexercises/exercises/compiler/Compiler.scala
compiler/src/main/scala/org/scalaexercises/exercises/compiler/MethodBodyReader.scala
compiler/src/main/scala/org/scalaexercises/exercises/compiler/SourceTextExtraction.scala
compiler/src/main/scala/org/scalaexercises/exercises/compiler/TreeGen.scala
compiler/src/main/scala/org/scalaexercises/exercises/compiler/comments.scala
compiler/src/main/scala/org/scalaexercises/exercises/compiler/formatting.scala
compiler/src/test/scala/org/scalaexercises/exercises/compiler/CommentParsingRenderingSpec.scala
compiler/src/test/scala/org/scalaexercises/exercises/compiler/CommentRenderingRegressions.scala
compiler/src/test/scala/org/scalaexercises/exercises/compiler/CompilerSpec.scala
compiler/src/test/scala/org/scalaexercises/exercises/compiler/MethodBodyReaderSpec.scala
compiler/src/test/scala/org/scalaexercises/exercises/compiler/SourceTextExtractionSpec.scala
compiler/src/test/scala/org/scalaexercises/exercises/compiler/TreeGenSpec.scala
project/ProjectPlugin.scala
project/build.properties

Updated compiler module and tests passing in that module. Modules client, server and sbt-exercise haven't been updated, so they won't compile. The following tasks are to update the mentioned modules and after that, travis should pass the tests.

Compiler Module Update

---

compiler/src/main/scala/org/scalaexercises/exercises/compiler/SourceTextExtraction.scala
compiler/src/test/scala/org/scalaexercises/exercises/compiler/SourceTextExtractionSpec.scala
project/plugins.sbt
sbt-exercise/src/main/scala/org/scalaexercises/exercises/sbtexercise/ExerciseCompilerPlugin.scala
sbt-exercise/src/sbt-test/sbt-exercise/basic/build.sbt
sbt-exercise/src/sbt-test/sbt-exercise/basic/test
sbt-exercise/src/sbt-test/sbt-exercise/scalariform/build.sbt
sbt-exercise/src/sbt-test/sbt-exercise/scalariform/project/plugins.sbt
version.sbt

This PR updates the sbt plugin. Scripted tests have been executed and passing. Modules client and server haven't been modified yet, so the code won't fully compile. In consequence, travis build will fail. Remaining tasks are to update the mentioned modules and its tests.

Plugin sbt module update

---

client/src/main/scala/Api.scala
client/src/main/scala/Ui.scala
client/src/main/scala/scripts/ExercisesJS.scala
client/src/main/scala/utils/DomHandler.scala
client/src/main/scala/utils/Implicits.scala
client/src/test/scala/Factories.scala
client/src/test/scala/ModelSpec.scala

This PR updates client module. The code for that module compiles and pass tests. There's still modules which needs reparation so the whole project may not compile. In consequence, travis build will fail. Remaining task is to update the server module and its tests if needed.

Client Module Update

---

.travis.yml
Gemfile.lock

* Set Heroku blessed Bundler version (2.0.2)

Set Heroku blessed Bundler version (2.0.2)

---

Gemfile
Procfile
project/ProjectPlugin.scala

It tries to setup newrelic through the javaagent config key.

Fix Newrelic

---

build.sbt
compiler/src/main/scala/org/scalaexercises/exercises/compiler/Compiler.scala
project/ProjectPlugin.scala
server/app/org/scalaexercises/exercises/controllers/ApplicationController.scala
server/app/org/scalaexercises/exercises/controllers/OAuthController.scala

This PR:
* Upgrades dependencies to the latest version: circe, http4s, etc.
* Cleanups the build
* Upgrades code to the latest version of Github4s

Build Cleanup and Dependencies upgrade

---

project/ProjectPlugin.scala

Closes https://github.com/scala-exercises/scala-exercises/pull/709

Upgrades scalajsdom

---

.scalafmt.conf
client/src/main/scala/utils/DomHandler.scala
core/shared/src/main/scala/org/scalaexercises/algebra/exercises.scala
core/shared/src/main/scala/org/scalaexercises/algebra/progress/progress.scala
core/shared/src/main/scala/org/scalaexercises/algebra/user.scala
core/shared/src/main/scala/org/scalaexercises/types/exercises.scala
server/app/org/scalaexercises/exercises/Actions.scala
server/app/org/scalaexercises/exercises/controllers/ApplicationController.scala
server/app/org/scalaexercises/exercises/persistence/domain/package.scala

Update scalafmt-core to 2.6.0

---

.scalafmt.conf
server/app/org/scalaexercises/exercises/Actions.scala
server/app/org/scalaexercises/exercises/controllers/ApplicationController.scala
server/app/org/scalaexercises/exercises/persistence/domain/package.scala

Update scalafmt-core to 2.6.1

---

server/app/views/templates/library/index.scala.html

should fixed issue  https://github.com/scala-exercises/exercises-stdlib/issues/286

fixed link
